_:
	gcc -Wall -O0 -g -std=gnu11 main.c debug.c bufs.c libs.c pnglitch.c -lpng -lz -pthread -o ../glitch
debug:
	gcc -Wall -O0 -g -std=gnu11 -DDEBUG main.c debug.c bufs.c libs.c pnglitch.c -lpng -lz -pthread -o ../glitch
